# Generated by Django 5.1.1 on 2024-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
